"""AI second opinion on the automatic column mapping -- not a replacement
for tgdatabridge.core.type_mapping's deterministic engine-to-engine rules
(nothing here ever changes a generated type; see ddl_generator.py, which is
what actually decides target_type), but a review layer on top of it.

Why a review layer rather than the AI choosing types itself: the
deterministic mapper in type_mapping.py is exhaustively tested per engine
pair and is what the generated DDL actually uses -- correctness there must
not depend on a network call or a model's mood. What a rule table cannot
easily do is notice that, say, a NUMBER(20) source column mapping to a
target BIGINT is a real truncation risk for a table whose row_count_estimate
suggests it holds large values, or that a column named `legacy_flag`
converted to a bare CHAR(1) probably deserves a comment for the reviewer.
That's the kind of contextual, "does this actually make sense" judgment
call this module asks the model for -- after conversion has already run,
never instead of it.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import List

from tgdatabridge.ai.ai_client import AiClient, AiError
from tgdatabridge.core.schema_model import Table

_VALID_RISK_LEVELS = ("none", "low", "medium", "high")

_SYSTEM_PROMPT = (
    "You are a careful database migration reviewer. You are shown one "
    "table's columns as they were converted from a source database engine "
    "to a target engine by an automatic, rule-based type mapper. Your job "
    "is only to flag anything that looks like a real risk in that "
    "conversion (silent truncation, precision loss, a nullability change "
    "that could break existing data, a default value that won't parse on "
    "the target, an identity/auto-increment column that lost that "
    "property) -- not to suggest stylistic alternatives. Most columns in a "
    "normal table deserve risk \"none\" with no note. Reply with ONLY a "
    "JSON array, no prose before or after it, no markdown fence. Each "
    "element: {\"column\": <exact column name from the input>, "
    "\"risk\": \"none\"|\"low\"|\"medium\"|\"high\", \"note\": <short "
    "explanation, empty string if risk is \"none\">, "
    "\"suggested_target_type\": <a better target type if you have one, "
    "otherwise null>}. Include every column from the input exactly once, "
    "in the same order."
)


@dataclass
class MappingSuggestion:
    column: str
    risk: str
    note: str
    suggested_target_type: str = ""


def review_table_mapping(client: AiClient, table: Table, target_engine: str) -> List[MappingSuggestion]:
    """Ask the configured AI backend to review `table`'s already-converted
    columns (source_type -> target_type, as generated by this run's
    Convert Schema step) and flag anything risky. Returns [] for a table
    with no columns. Raises AiError -- unchanged -- for anything that goes
    wrong; callers (the GUI's AI Review dialog, primarily) show that
    message rather than silently swallowing it, since a silent failure
    here would look like "the AI found nothing to flag", which is a very
    different thing from "the AI could not be reached"."""
    if not table.columns:
        return []

    lines = [f"Target engine: {target_engine}", f"Table: {table.schema}.{table.name}", "Columns:"]
    for col in table.columns:
        target = col.target_type_override or col.target_type or "(not yet converted)"
        lines.append(
            f"  - {col.name}: source type {col.data_type!r} -> target type {target!r}, "
            f"nullable={col.nullable}, identity={col.identity}"
            + (f", default={col.default!r}" if col.default else "")
        )
    user_prompt = "\n".join(lines)

    raw = client.complete_json(_SYSTEM_PROMPT, user_prompt)
    if not isinstance(raw, list):
        raise AiError("The AI's mapping review did not come back as a list as requested.")

    known_columns = {col.name for col in table.columns}
    suggestions: List[MappingSuggestion] = []
    for item in raw:
        if not isinstance(item, dict):
            continue
        name = item.get("column")
        if name not in known_columns:
            # A hallucinated or renamed column would be actively
            # misleading in a review UI -- silently drop it rather than
            # show a suggestion attached to a column that doesn't exist.
            continue
        risk = item.get("risk") if item.get("risk") in _VALID_RISK_LEVELS else "none"
        suggestions.append(MappingSuggestion(
            column=name,
            risk=risk,
            note=str(item.get("note") or ""),
            suggested_target_type=str(item.get("suggested_target_type") or ""),
        ))
    return suggestions


__all__ = ["MappingSuggestion", "review_table_mapping"]
